CREATE OR REPLACE FUNCTION percent_change(value FLOAT, base FLOAT)
  RETURNS FLOAT
AS
$$
SELECT 100 * ((value / base) - 1)
$$
  LANGUAGE SQL
  IMMUTABLE
  RETURNS NULL ON NULL INPUT;

CREATE OR REPLACE FUNCTION percent_change(value NUMERIC, base NUMERIC)
  RETURNS NUMERIC
AS
$$
SELECT 100 * ((value / base) - 1)
$$
  LANGUAGE SQL
  IMMUTABLE
  RETURNS NULL ON NULL INPUT;

